=== MSSGIT2128/MSS_UAT/DunningLetters/DunningLetters/Files/NS_FU/Fusion/MainFlow/Request/SampleRequestSchema.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"$id": "http://example.com/example.json",
	"type": "object",
	"title": "The root schema",
	"description": "The root schema comprises the entire JSON document.",
	"default": {},
	"examples": [
		{
			"RequestId": 1614148362011,
			"Operation": "Create",
			"Type": "Journal",
			"Data": {}
		}
	],
	"required": [
		"RequestId",
		"Operation",
		"Type",
		"Data"
	],
	"properties": {
		"RequestId": {
			"$id": "#/properties/RequestId",
			"type": "integer",
			"title": "The RequestId schema",
			"description": "An explanation about the purpose of this instance.",
			"default": 0,
			"examples": [
				1614148362011
			]
		},
		"Operation": {
			"$id": "#/properties/Operation",
			"type": "string",
			"title": "The Operation schema",
			"description": "An explanation about the purpose of this instance.",
			"default": "",
			"examples": [
				"Create"
			]
		},
		"Type": {
			"$id": "#/properties/Type",
			"type": "string",
			"title": "The Type schema",
			"description": "An explanation about the purpose of this instance.",
			"default": "",
			"examples": [
				"Journal"
			]
		},
		"Data": {
			"$id": "#/properties/Data",
			"type": "object",
			"title": "The Data schema",
			"description": "An explanation about the purpose of this instance.",
			"default": {},
			"examples": [
				{}
			],
			"required": [],
			"additionalProperties": true
		}
	},
	"additionalProperties": true
}

=== MSSGIT2128/MSS_UAT/NetSuiteWebhook/NetSuiteWebhook/Files/NS_FU/NetSuite/Sample Payloads/CreateJournalSample.json
{
	"RequestId": 654567898765434,
	"Operation": "Create",
	"Type": "Journal",
	"Data": {
		"BatchName": "Test Batch from API",
		"BatchDescription": "Test Batch from API",
		"LedgerId": "300000002335898",
		"AccountingPeriodName": "Feb-21",
		"AccountingDate": "2021-02-08",
		"UserSourceName": "SIS GL Interface",
		"UserCategoryName": "SIS GL Interface",
		"ErrorToSuspenseFlag": "false",
		"SummaryFlag": "false",
		"ImportDescriptiveFlexField": "Y",
		"GlInterface": [
			{
				"Reference4": "Test Journal from API",
				"Reference5": "Test Journal from API",
				"LedgerId": "300000002335898",
				"PeriodName": "Feb-21",
				"AccountingDate": "2021-02-08",
				"UserJeSourceName": "SIS GL Interface",
				"UserJeCategoryName": "SIS GL Interface",
				"Segment1": "101",
				"Segment2": "999",
				"Segment3": "1111101",
				"Segment4": "999",
				"Segment5": "999",
				"Segment6": "9999",
				"Segment7": "99999",
				"Segment8": "99999",
				"Segment9": "999",
				"Segment10": "999",
				"Segment11": "9999",
				"CurrencyCode": "INR",
				"EnteredDrAmount": {
					"@currencyCode": "INR",
					"#text": "2000"
				},
				"AccountedDr": "2000",
				"Reference1": "Test Journal from API",
				"Reference2": "Test Journal from API",
				"Attribute1": "Test Attribute1",
				"Attribute2": "Test Attribute2",
				"Attribute3": "Test Attribute3",
				"Attribute4": "Test Attribute4",
				"SetOfBooksId": "300000002335898",
				"TransactionDate": "2021-02-09",
				"GroupId": "123"
			},
			{
				"Reference4": "Test Journal from API",
				"Reference5": "Test Journal from API",
				"LedgerId": "300000002335898",
				"PeriodName": "Feb-21",
				"AccountingDate": "2021-02-08",
				"UserJeSourceName": "SIS GL Interface",
				"UserJeCategoryName": "SIS GL Interface",
				"Segment1": "101",
				"Segment2": "999",
				"Segment3": "1111102",
				"Segment4": "999",
				"Segment5": "999",
				"Segment6": "9999",
				"Segment7": "99999",
				"Segment8": "99999",
				"Segment9": "999",
				"Segment10": "999",
				"Segment11": "9999",
				"CurrencyCode": "INR",
				"EnteredCrAmount": {
					"@currencyCode": "INR",
					"#text": "1000"
				},
				"AccountedCr": "1000",
				"Reference1": "Test Journal from API",
				"Reference2": "Test Journal from API",
				"Attribute1": "Test Attribute1",
				"Attribute2": "Test Attribute2",
				"Attribute3": "Test Attribute3",
				"Attribute4": "Test Attribute4",
				"SetOfBooksId": "300000002335898",
				"TransactionDate": "2021-02-09",
				"GroupId": "123"
			},
			{
				"Reference4": "Test Journal from API",
				"Reference5": "Test Journal from API",
				"LedgerId": "300000002335898",
				"PeriodName": "Feb-21",
				"AccountingDate": "2021-02-08",
				"UserJeSourceName": "SIS GL Interface",
				"UserJeCategoryName": "SIS GL Interface",
				"Segment1": "101",
				"Segment2": "999",
				"Segment3": "1111105",
				"Segment4": "999",
				"Segment5": "999",
				"Segment6": "9999",
				"Segment7": "99999",
				"Segment8": "99999",
				"Segment9": "999",
				"Segment10": "999",
				"Segment11": "9999",
				"CurrencyCode": "INR",
				"EnteredCrAmount": {
					"@currencyCode": "INR",
					"#text": "1000"
				},
				"AccountedCr": "1000",
				"Reference1": "Test Journal from API",
				"Reference2": "Test Journal from API",
				"Attribute1": "Test Attribute1",
				"Attribute2": "Test Attribute2",
				"Attribute3": "Test Attribute3",
				"Attribute4": "Test Attribute4",
				"SetOfBooksId": "300000002335898",
				"TransactionDate": "2021-02-09",
				"GroupId": "123"
			}
		]
	}
}

=== MSSGIT2128/MSS_UAT/DunningLetters/DunningLetters/Files/NS_FU/NetSuite/Sample Payloads/CreateCustomerMSSContactSample.json
{
	"RequestId": 654567898765434,
	"Operation": "Create",
	"Type": "MSSContact",
	"Data": {
		"CreatedByModule": "SIS",
		"PersonProfile": {
			"PersonFirstName": "MgFN_02",
			"PersonLastName": "MgLN_02",
			"CreatedByModule": "SIS"
		},
		"Relationship": {
			"SubjectType": "PERSON",
			"SubjectTableName": "HZ_PARTIES",
			"ObjectId": "300000003009608",
			"ObjectType": "ORGANIZATION",
			"ObjectTableName": "HZ_PARTIES",
			"RelationshipCode": "CONTACT_OF",
			"RelationshipType": "CONTACT",
			"StartDate": "2020-09-24",
			"CreatedByModule": "SIS",
			"OrganizationContact": {
				"ContactNumber": "MgContact02",
				"CreatedByModule": "SIS",
				"OrganizationContactRole": {
					"RoleType": "CONTACT",
					"PrimaryFlag": true,
					"CreatedByModule": "SIS"
				}
			},
			"Email": {
				"OwnerTableName": "HZ_PARTIES",
				"PrimaryFlag": true,
				"CreatedByModule": "SIS",
				"ContactPointPurpose": "BUSINESS",
				"StartDate": "2020-09-24",
				"EmailAddress": "test2@test.com"
			},
			"Phone": {
				"OwnerTableName": "HZ_PARTIES",
				"PrimaryFlag": true,
				"CreatedByModule": "SIS",
				"StartDate": "2020-09-24",
				"PhoneCountryCode": "test2@test.com",
				"PhoneNumber": "test2@test.com"
			}
		}
	}
}

=== MSSGIT2128/MSS_UAT/Rolecall_To_Fusion/Rolecall_To_Fusion/Files/NS_FU/NetSuite/Sample Payloads/ApplyOnAccountCreditMemoSample.json
{
	"RequestId": 654567898765434,
 	"Operation": "Create",
	"Type": "ApplyOnAccountCreditMemo",
	"Data": {
		"applyOnAccountCreditMemo": {
			"BusinessUnit": "SXP Group BU",
			"CreditMemoTrxNumber": "204763",
			"InvoiceTrxNumber": "204763",
			"AmountApplied": 5.5,
			"ApplyDate": "2021-03-31",
			"GlDate": "2021-03-31",
			"InvoiceLineNumber": "1",
			"Comments": ""
		}
	}
}

=== MSSGIT2128/MSS_UAT/Rolecall_To_Fusion/Rolecall_To_Fusion/Files/NS_FU/NetSuite/Sample Payloads/CreateARCreditMemo.json
{
  "RequestId": 125792021021217,
  "Operation":"Create",
   "Type":"Credit",
   "Data":{
      "Lines": [
         {
            "OrgId": "300000001869043",
            "BillCustomerAccountNumber": "1",
            "BillCustomerSiteNumber": "2014",
            "BatchSourceName": "SIS_AR_IMPORT",
            "CurrencyCode": "INR",
            "CustomerTrxTypeName": "Credit Memo",
            "Description": "Test Debit Memo",
            "LineType": "LINE",
            "Quantity": "1",
            "TrxNumber": "0710202003CM",
            "TrxDate": "2020-10-07",
            "GlDate": "2020-10-07",
            "UnitSellingPrice": "-225",
            "AmountIncludesTax": "N",
            "TaxJurisdictionCode": "AU GST",
			"Tax": "AU GST",
			"TaxRateCode": "AU GST 10%",
			"TaxRegimeCode": "AU GST REGIME",
			"Taxable": "Y",
			"ReasonCodeMeaning": "Billing",
			"Comments": "Test Comments",
			"LegalEntityId": "300000001608257",
			"ProductFiscClassification": "12.00-30049099",
            "TransactionInterfaceLineDff": {
               "Type": "Otherinvoicedetails",
               "Content": "OtherInvoiceDetails",
               "ContentDisplayValue": "OtherInvoiceDetails",
               "OtherDetails": "0710202003CM-1"
            }
         },
         {
            "OrgId": "300000001869043",
            "BillCustomerAccountNumber": "1",
            "BillCustomerSiteNumber": "2014",
            "BatchSourceName": "SIS_AR_IMPORT",
            "CurrencyCode": "INR",
            "CustomerTrxTypeName": "Credit Memo",
            "Description": "Test Debit Memo",
            "LineType": "LINE",
            "Quantity": "1",
            "TrxNumber": "0710202003CM",
            "TrxDate": "2020-10-07",
            "GlDate": "2020-10-07",
            "UnitSellingPrice": "-225",
            "AmountIncludesTax": "N",
			 "TaxJurisdictionCode": "AU GST",
			"Tax": "AU GST",
			"TaxRateCode": "AU GST 10%",
			"TaxRegimeCode": "AU GST REGIME",
			"Taxable": "Y",
			"ReasonCodeMeaning": "Billing",
			"Comments": "Test Comments",
			"LegalEntityId": "300000001608257",
            "ProductFiscClassification": "12.00-30049099",
            "TransactionInterfaceLineDff": {
               "Type": "Otherinvoicedetails",
               "Content": "OtherInvoiceDetails",
               "ContentDisplayValue": "OtherInvoiceDetails",
               "OtherDetails": "0710202003CM-1"
            }
         }
      ],
      "processControl": {
         "partialFailureAllowed": "false"
      }
   }
}

=== MSSGIT2128/MSS_UAT/DunningLetters/DunningLetters/Files/NS_FU/NetSuite/Sample Payloads/AR_CN_invoiceAttachment.json
{
	"RequestId": 1234567890,
	"Operation": "Create",
	"Type": "UploadAttachment",
	"Data": {
		"entityName": "RA_CUSTOMER_TRX_ALL",
		"categoryName": "CUSTOMER_TRX",
		"allowDuplicate": "Yes",
		"attachmentRows": {
			"UserKeyA": "SXP Group BU",
			"UserKeyB": "CN12345",
			"UserKeyC": "SIS_AR_IMPORT",
			"UserKeyD": "NetSuite will pass null.  Grab value from the CustomerTransactionId generated from the GET_AR_CreditResponse",
			"AttachmentType": "FILE",
			"Title": "TESTAV.txt",
			"Content": "BASE64_Content"
		}
	}
}

=== MSSGIT2128/MSS_UAT/NetSuiteWebhook/NetSuiteWebhook/Files/NS_FU/NetSuite/Sample Payloads/DisputeSample.json
{
	"RequestId": 654567898765434,
	"Operation": "Create",
	"Type": "Dispute",
	"Data": {
		"operationMode": "SINGLE",
		"object": {
			"EntityName": "Receivables Invoice",
			"ContextValue": "Dispute Management",
			"UserKeyA": "12000",
			"DFFAttributes": {
				"ATTRIBUTE3": "N",
				"ATTRIBUTE8": "2020-12-01",
				"ATTRIBUTE9": "Y",
				"ATTRIBUTE10": "Test Distribute Reason",
				"ATTRIBUTE11": "2020-12-31"
			}
		}
	}
}

=== MSSGIT2128/MSS_UAT/DunningLetters/DunningLetters/Files/NS_FU/NetSuite/Sample Payloads/CreditApplyToARInvoice.json
{
	"RequestId": 123456789,
	"Operation": "Create",
	"Type": "CreditDistribution",
	"Data": {
		"applyOnAccountCreditMemo": {
			"BusinessUnit": "Dusters Total Solutions Services Pvt. Ltd.",
			"CreditMemoTrxNumber": "17910202003CM",
			"InvoiceTrxNumber": "22003",
			"AmountApplied": "100",
			"ApplyDate": "2020-10-22",
			"GlDate": "2020-10-22",
			"InvoiceLineNumber": "1",
			"Comments": "SOAP API APPLY"
		}
	}
}
