=== MSSGIT2128/MSS_UAT/CopyOfRolecall_To_Fusion/Files/RoleCall_FU/Fusion/Organization/Update/GetURL/ResponseSchema.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"$id": "http://example.com/example.json",
	"type": "object",
	"title": "The root schema",
	"description": "The root schema comprises the entire JSON document.",
	"default": {},
	"examples": [
		{
			"items": [
				{
					"ValueId": 85040
				}
			],
			"count": 1,
			"hasMore": false,
			"limit": 25,
			"offset": 0,
			"links": [
				{
					"rel": "self",
					"href": "https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/Customer%20Site%20SIS_COA/child/values",
					"name": "values",
					"kind": "collection"
				}
			]
		}
	],
	"required": [
		"items",
		"count",
		"hasMore",
		"limit",
		"offset",
		"links"
	],
	"properties": {
		"items": {
			"$id": "#/properties/items",
			"type": "array",
			"title": "The items schema",
			"description": "An explanation about the purpose of this instance.",
			"default": [],
			"examples": [
				[
					{
						"ValueId": 85040
					}
				]
			],
			"additionalItems": true,
			"items": {
				"$id": "#/properties/items/items",
				"anyOf": [
					{
						"$id": "#/properties/items/items/anyOf/0",
						"type": "object",
						"title": "The first anyOf schema",
						"description": "An explanation about the purpose of this instance.",
						"default": {},
						"examples": [
							{
								"ValueId": 85040
							}
						],
						"required": [
							"ValueId"
						],
						"properties": {
							"ValueId": {
								"$id": "#/properties/items/items/anyOf/0/properties/ValueId",
								"type": "integer",
								"title": "The ValueId schema",
								"description": "An explanation about the purpose of this instance.",
								"default": 0,
								"examples": [
									85040
								]
							}
						},
						"additionalProperties": true
					}
				]
			}
		},
		"count": {
			"$id": "#/properties/count",
			"type": "integer",
			"title": "The count schema",
			"description": "An explanation about the purpose of this instance.",
			"default": 0,
			"examples": [
				1
			]
		},
		"hasMore": {
			"$id": "#/properties/hasMore",
			"type": "boolean",
			"title": "The hasMore schema",
			"description": "An explanation about the purpose of this instance.",
			"default": false,
			"examples": [
				false
			]
		},
		"limit": {
			"$id": "#/properties/limit",
			"type": "integer",
			"title": "The limit schema",
			"description": "An explanation about the purpose of this instance.",
			"default": 0,
			"examples": [
				25
			]
		},
		"offset": {
			"$id": "#/properties/offset",
			"type": "integer",
			"title": "The offset schema",
			"description": "An explanation about the purpose of this instance.",
			"default": 0,
			"examples": [
				0
			]
		},
		"links": {
			"$id": "#/properties/links",
			"type": "array",
			"title": "The links schema",
			"description": "An explanation about the purpose of this instance.",
			"default": [],
			"examples": [
				[
					{
						"rel": "self",
						"href": "https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/Customer%20Site%20SIS_COA/child/values",
						"name": "values",
						"kind": "collection"
					}
				]
			],
			"additionalItems": true,
			"items": {
				"$id": "#/properties/links/items",
				"anyOf": [
					{
						"$id": "#/properties/links/items/anyOf/0",
						"type": "object",
						"title": "The first anyOf schema",
						"description": "An explanation about the purpose of this instance.",
						"default": {},
						"examples": [
							{
								"rel": "self",
								"href": "https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/Customer%20Site%20SIS_COA/child/values",
								"name": "values",
								"kind": "collection"
							}
						],
						"required": [
							"rel",
							"href",
							"name",
							"kind"
						],
						"properties": {
							"rel": {
								"$id": "#/properties/links/items/anyOf/0/properties/rel",
								"type": "string",
								"title": "The rel schema",
								"description": "An explanation about the purpose of this instance.",
								"default": "",
								"examples": [
									"self"
								]
							},
							"href": {
								"$id": "#/properties/links/items/anyOf/0/properties/href",
								"type": "string",
								"title": "The href schema",
								"description": "An explanation about the purpose of this instance.",
								"default": "",
								"examples": [
									"https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/Customer%20Site%20SIS_COA/child/values"
								]
							},
							"name": {
								"$id": "#/properties/links/items/anyOf/0/properties/name",
								"type": "string",
								"title": "The name schema",
								"description": "An explanation about the purpose of this instance.",
								"default": "",
								"examples": [
									"values"
								]
							},
							"kind": {
								"$id": "#/properties/links/items/anyOf/0/properties/kind",
								"type": "string",
								"title": "The kind schema",
								"description": "An explanation about the purpose of this instance.",
								"default": "",
								"examples": [
									"collection"
								]
							}
						},
						"additionalProperties": true
					}
				]
			}
		}
	},
	"additionalProperties": true
}

=== MSSGIT2128/MSS_UAT/Rolecall_To_Fusion/Rolecall_To_Fusion/Files/NS_FU/Fusion/Dimensions/CustomerExist/Response/CustomerSiteCheckCheckResponseSample.json
{
	"items": [
		{
			"ValueId": 311039,
			"IndependentValue": null,
			"IndependentValueNumber": null,
			"IndependentValueDate": null,
			"IndependentValueTimestamp": null,
			"Value": "J14100",
			"ValueNumber": null,
			"ValueDate": null,
			"ValueTimestamp": null,
			"TranslatedValue": null,
			"Description": "Abi Group [49770]",
			"EnabledFlag": "Y",
			"StartDateActive": null,
			"EndDateActive": null,
			"SortOrder": null,
			"SummaryFlag": "N",
			"DetailPostingAllowed": "Y",
			"DetailBudgetingAllowed": "Y",
			"AccountType": null,
			"ControlAccount": null,
			"ReconciliationFlag": null,
			"FinancialCategory": null,
			"ExternalDataSource": null,
			"CreationDate": "2021-04-06T07:58:44+00:00",
			"CreatedBy": "SIS_INTEGRATION",
			"LastUpdateDate": "2021-04-06T07:58:44.106+00:00",
			"LastUpdatedBy": "SIS_INTEGRATION",
			"links": [
				{
					"rel": "self",
					"href": "https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/Customer%20Site%20SIS_COA/child/values/311039",
					"name": "values",
					"kind": "item"
				},
				{
					"rel": "canonical",
					"href": "https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/Customer%20Site%20SIS_COA/child/values/311039",
					"name": "values",
					"kind": "item"
				},
				{
					"rel": "parent",
					"href": "https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/Customer%20Site%20SIS_COA",
					"name": "valueSets",
					"kind": "item"
				},
				{
					"rel": "child",
					"href": "https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/Customer%20Site%20SIS_COA/child/values/311039/child/valuesDFF",
					"name": "valuesDFF",
					"kind": "collection"
				}
			]
		}
	],
	"count": 1,
	"hasMore": false,
	"limit": 25,
	"offset": 0,
	"links": [
		{
			"rel": "self",
			"href": "https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/Customer%20Site%20SIS_COA/child/values",
			"name": "values",
			"kind": "collection"
		}
	]
}
