=== MSSGIT2128/MSS_UAT/Redmap_To_Fusion/Files/RM_FU/Fusion/Currency_rate/Response/CurrencyResponseSchema.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"$id": "http://example.com/example.json",
	"type": "object",
	"title": "The root schema",
	"description": "The root schema comprises the entire JSON document.",
	"default": {},
	"examples": [
		{
			"items": [
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-01",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-02",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-03",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-04",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-05",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-06",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-07",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-08",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-09",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-10",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-11",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-12",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-13",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-14",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-15",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-16",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-17",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-18",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-19",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-20",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-21",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-22",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-23",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-24",
					"ConversionRate": 70
				},
				{
					"FromCurrency": "USD",
					"ToCurrency": "INR",
					"UserConversionType": "Corporate",
					"ConversionDate": "2020-10-25",
					"ConversionRate": 70
				}
			],
			"count": 25,
			"hasMore": true,
			"limit": 25,
			"offset": 0,
			"links": [
				{
					"rel": "self",
					"href": "https://fa-epnz-dev1-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/currencyRates",
					"name": "currencyRates",
					"kind": "collection"
				}
			]
		}
	],
	"required": [
		"items",
		"count",
		"hasMore",
		"limit",
		"offset",
		"links"
	],
	"properties": {
		"items": {
			"$id": "#/properties/items",
			"type": "array",
			"title": "The items schema",
			"description": "An explanation about the purpose of this instance.",
			"default": [],
			"examples": [
				[
					{
						"FromCurrency": "USD",
						"ToCurrency": "INR",
						"UserConversionType": "Corporate",
						"ConversionDate": "2020-10-01",
						"ConversionRate": 70
					},
					{
						"FromCurrency": "USD",
						"ToCurrency": "INR",
						"UserConversionType": "Corporate",
						"ConversionDate": "2020-10-02",
						"ConversionRate": 70
					}
				]
			],
			"additionalItems": true,
			"items": {
				"$id": "#/properties/items/items",
				"anyOf": [
					{
						"$id": "#/properties/items/items/anyOf/0",
						"type": "object",
						"title": "The first anyOf schema",
						"description": "An explanation about the purpose of this instance.",
						"default": {},
						"examples": [
							{
								"FromCurrency": "USD",
								"ToCurrency": "INR",
								"UserConversionType": "Corporate",
								"ConversionDate": "2020-10-01",
								"ConversionRate": 70
							}
						],
						"required": [
							"FromCurrency",
							"ToCurrency",
							"UserConversionType",
							"ConversionDate",
							"ConversionRate"
						],
						"properties": {
							"FromCurrency": {
								"$id": "#/properties/items/items/anyOf/0/properties/FromCurrency",
								"type": "string",
								"title": "The FromCurrency schema",
								"description": "An explanation about the purpose of this instance.",
								"default": "",
								"examples": [
									"USD"
								]
							},
							"ToCurrency": {
								"$id": "#/properties/items/items/anyOf/0/properties/ToCurrency",
								"type": "string",
								"title": "The ToCurrency schema",
								"description": "An explanation about the purpose of this instance.",
								"default": "",
								"examples": [
									"INR"
								]
							},
							"UserConversionType": {
								"$id": "#/properties/items/items/anyOf/0/properties/UserConversionType",
								"type": "string",
								"title": "The UserConversionType schema",
								"description": "An explanation about the purpose of this instance.",
								"default": "",
								"examples": [
									"Corporate"
								]
							},
							"ConversionDate": {
								"$id": "#/properties/items/items/anyOf/0/properties/ConversionDate",
								"type": "string",
								"title": "The ConversionDate schema",
								"description": "An explanation about the purpose of this instance.",
								"default": "",
								"examples": [
									"2020-10-01"
								]
							},
							"ConversionRate": {
								"$id": "#/properties/items/items/anyOf/0/properties/ConversionRate",
								"type": "integer",
								"title": "The ConversionRate schema",
								"description": "An explanation about the purpose of this instance.",
								"default": 0,
								"examples": [
									70
								]
							}
						},
						"additionalProperties": true
					}
				]
			}
		},
		"count": {
			"$id": "#/properties/count",
			"type": "integer",
			"title": "The count schema",
			"description": "An explanation about the purpose of this instance.",
			"default": 0,
			"examples": [
				25
			]
		},
		"hasMore": {
			"$id": "#/properties/hasMore",
			"type": "boolean",
			"title": "The hasMore schema",
			"description": "An explanation about the purpose of this instance.",
			"default": false,
			"examples": [
				true
			]
		},
		"limit": {
			"$id": "#/properties/limit",
			"type": "integer",
			"title": "The limit schema",
			"description": "An explanation about the purpose of this instance.",
			"default": 0,
			"examples": [
				25
			]
		},
		"offset": {
			"$id": "#/properties/offset",
			"type": "integer",
			"title": "The offset schema",
			"description": "An explanation about the purpose of this instance.",
			"default": 0,
			"examples": [
				0
			]
		},
		"links": {
			"$id": "#/properties/links",
			"type": "array",
			"title": "The links schema",
			"description": "An explanation about the purpose of this instance.",
			"default": [],
			"examples": [
				[
					{
						"rel": "self",
						"href": "https://fa-epnz-dev1-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/currencyRates",
						"name": "currencyRates",
						"kind": "collection"
					}
				]
			],
			"additionalItems": true,
			"items": {
				"$id": "#/properties/links/items",
				"anyOf": [
					{
						"$id": "#/properties/links/items/anyOf/0",
						"type": "object",
						"title": "The first anyOf schema",
						"description": "An explanation about the purpose of this instance.",
						"default": {},
						"examples": [
							{
								"rel": "self",
								"href": "https://fa-epnz-dev1-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/currencyRates",
								"name": "currencyRates",
								"kind": "collection"
							}
						],
						"required": [
							"rel",
							"href",
							"name",
							"kind"
						],
						"properties": {
							"rel": {
								"$id": "#/properties/links/items/anyOf/0/properties/rel",
								"type": "string",
								"title": "The rel schema",
								"description": "An explanation about the purpose of this instance.",
								"default": "",
								"examples": [
									"self"
								]
							},
							"href": {
								"$id": "#/properties/links/items/anyOf/0/properties/href",
								"type": "string",
								"title": "The href schema",
								"description": "An explanation about the purpose of this instance.",
								"default": "",
								"examples": [
									"https://fa-epnz-dev1-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/currencyRates"
								]
							},
							"name": {
								"$id": "#/properties/links/items/anyOf/0/properties/name",
								"type": "string",
								"title": "The name schema",
								"description": "An explanation about the purpose of this instance.",
								"default": "",
								"examples": [
									"currencyRates"
								]
							},
							"kind": {
								"$id": "#/properties/links/items/anyOf/0/properties/kind",
								"type": "string",
								"title": "The kind schema",
								"description": "An explanation about the purpose of this instance.",
								"default": "",
								"examples": [
									"collection"
								]
							}
						},
						"additionalProperties": true
					}
				]
			}
		}
	},
	"additionalProperties": true
}

=== MSSGIT2128/MSS_UAT/Redmap_To_Fusion/Files/RM_FU/Fusion/Currency_rate/Response/CurrencySampleResponse.json
{
	"items": [
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-01",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-02",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-03",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-04",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-05",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-06",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-07",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-08",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-09",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-10",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-11",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-12",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-13",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-14",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-15",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-16",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-17",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-18",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-19",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-20",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-21",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-22",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-23",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-24",
			"ConversionRate": 70
		},
		{
			"FromCurrency": "USD",
			"ToCurrency": "INR",
			"UserConversionType": "Corporate",
			"ConversionDate": "2020-10-25",
			"ConversionRate": 70
		}
	],
	"count": 25,
	"hasMore": true,
	"limit": 25,
	"offset": 0,
	"links": [
		{
			"rel": "self",
			"href": "https://fa-epnz-dev1-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/currencyRates",
			"name": "currencyRates",
			"kind": "collection"
		}
	]
}
