=== MSSGIT2128/MSS_UAT/NetSuiteWebhook/NetSuiteWebhook/Files/NS_FU/NetSuite/CreateCustomerMSSContactAssignmentSchema.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"$id": "http://example.com/example.json",
	"type": "object",
	"title": "The root schema",
	"description": "The root schema comprises the entire JSON document.",
	"default": {},
	"examples": [
		{
			"RequestId": 654567898765434,
			"Operation": "Create",
			"Type": "MSSContactAssignment",
			"Data": {
				"CustomerAccountId": "300000003444564",
				"PartyId": "300000003444540",
				"CustomerAccountContact": {
					"CustomerAccountId": "300000003444564",
					"PrimaryFlag": false,
					"RoleType": "CONTACT",
					"CreatedByModule": "SIS",
					"RelationshipId": "300000003444691",
					"CustomerAccountContactRole": {
						"ResponsibilityType": "BILL_TO",
						"PrimaryFlag": true,
						"CreatedByModule": "SIS"
					}
				}
			}
		}
	],
	"required": [
		"RequestId",
		"Operation",
		"Type",
		"Data"
	],
	"properties": {
		"RequestId": {
			"$id": "#/properties/RequestId",
			"type": "integer",
			"title": "The RequestId schema",
			"description": "An explanation about the purpose of this instance.",
			"default": 0,
			"examples": [
				654567898765434
			]
		},
		"Operation": {
			"$id": "#/properties/Operation",
			"type": "string",
			"title": "The Operation schema",
			"description": "An explanation about the purpose of this instance.",
			"default": "",
			"examples": [
				"Create"
			]
		},
		"Type": {
			"$id": "#/properties/Type",
			"type": "string",
			"title": "The Type schema",
			"description": "An explanation about the purpose of this instance.",
			"default": "",
			"examples": [
				"MSSContactAssignment"
			]
		},
		"Data": {
			"$id": "#/properties/Data",
			"type": "object",
			"title": "The Data schema",
			"description": "An explanation about the purpose of this instance.",
			"default": {},
			"examples": [
				{
					"CustomerAccountId": "300000003444564",
					"PartyId": "300000003444540",
					"CustomerAccountContact": {
						"CustomerAccountId": "300000003444564",
						"PrimaryFlag": false,
						"RoleType": "CONTACT",
						"CreatedByModule": "SIS",
						"RelationshipId": "300000003444691",
						"CustomerAccountContactRole": {
							"ResponsibilityType": "BILL_TO",
							"PrimaryFlag": true,
							"CreatedByModule": "SIS"
						}
					}
				}
			],
			"required": [
				"CustomerAccountId",
				"PartyId",
				"CustomerAccountContact"
			],
			"properties": {
				"CustomerAccountId": {
					"$id": "#/properties/Data/properties/CustomerAccountId",
					"type": "string",
					"title": "The CustomerAccountId schema",
					"description": "An explanation about the purpose of this instance.",
					"default": "",
					"examples": [
						"300000003444564"
					]
				},
				"PartyId": {
					"$id": "#/properties/Data/properties/PartyId",
					"type": "string",
					"title": "The PartyId schema",
					"description": "An explanation about the purpose of this instance.",
					"default": "",
					"examples": [
						"300000003444540"
					]
				},
				"CustomerAccountContact": {
					"$id": "#/properties/Data/properties/CustomerAccountContact",
					"type": "object",
					"title": "The CustomerAccountContact schema",
					"description": "An explanation about the purpose of this instance.",
					"default": {},
					"examples": [
						{
							"CustomerAccountId": "300000003444564",
							"PrimaryFlag": false,
							"RoleType": "CONTACT",
							"CreatedByModule": "SIS",
							"RelationshipId": "300000003444691",
							"CustomerAccountContactRole": {
								"ResponsibilityType": "BILL_TO",
								"PrimaryFlag": true,
								"CreatedByModule": "SIS"
							}
						}
					],
					"required": [
						"CustomerAccountId",
						"PrimaryFlag",
						"RoleType",
						"CreatedByModule",
						"RelationshipId",
						"CustomerAccountContactRole"
					],
					"properties": {
						"CustomerAccountId": {
							"$id": "#/properties/Data/properties/CustomerAccountContact/properties/CustomerAccountId",
							"type": "string",
							"title": "The CustomerAccountId schema",
							"description": "An explanation about the purpose of this instance.",
							"default": "",
							"examples": [
								"300000003444564"
							]
						},
						"PrimaryFlag": {
							"$id": "#/properties/Data/properties/CustomerAccountContact/properties/PrimaryFlag",
							"type": "boolean",
							"title": "The PrimaryFlag schema",
							"description": "An explanation about the purpose of this instance.",
							"default": false,
							"examples": [
								false
							]
						},
						"RoleType": {
							"$id": "#/properties/Data/properties/CustomerAccountContact/properties/RoleType",
							"type": "string",
							"title": "The RoleType schema",
							"description": "An explanation about the purpose of this instance.",
							"default": "",
							"examples": [
								"CONTACT"
							]
						},
						"CreatedByModule": {
							"$id": "#/properties/Data/properties/CustomerAccountContact/properties/CreatedByModule",
							"type": "string",
							"title": "The CreatedByModule schema",
							"description": "An explanation about the purpose of this instance.",
							"default": "",
							"examples": [
								"SIS"
							]
						},
						"RelationshipId": {
							"$id": "#/properties/Data/properties/CustomerAccountContact/properties/RelationshipId",
							"type": "string",
							"title": "The RelationshipId schema",
							"description": "An explanation about the purpose of this instance.",
							"default": "",
							"examples": [
								"300000003444691"
							]
						},
						"CustomerAccountContactRole": {
							"$id": "#/properties/Data/properties/CustomerAccountContact/properties/CustomerAccountContactRole",
							"type": "object",
							"title": "The CustomerAccountContactRole schema",
							"description": "An explanation about the purpose of this instance.",
							"default": {},
							"examples": [
								{
									"ResponsibilityType": "BILL_TO",
									"PrimaryFlag": true,
									"CreatedByModule": "SIS"
								}
							],
							"required": [
								"ResponsibilityType",
								"PrimaryFlag",
								"CreatedByModule"
							],
							"properties": {
								"ResponsibilityType": {
									"$id": "#/properties/Data/properties/CustomerAccountContact/properties/CustomerAccountContactRole/properties/ResponsibilityType",
									"type": "string",
									"title": "The ResponsibilityType schema",
									"description": "An explanation about the purpose of this instance.",
									"default": "",
									"examples": [
										"BILL_TO"
									]
								},
								"PrimaryFlag": {
									"$id": "#/properties/Data/properties/CustomerAccountContact/properties/CustomerAccountContactRole/properties/PrimaryFlag",
									"type": "boolean",
									"title": "The PrimaryFlag schema",
									"description": "An explanation about the purpose of this instance.",
									"default": false,
									"examples": [
										true
									]
								},
								"CreatedByModule": {
									"$id": "#/properties/Data/properties/CustomerAccountContact/properties/CustomerAccountContactRole/properties/CreatedByModule",
									"type": "string",
									"title": "The CreatedByModule schema",
									"description": "An explanation about the purpose of this instance.",
									"default": "",
									"examples": [
										"SIS"
									]
								}
							},
							"additionalProperties": true
						}
					},
					"additionalProperties": true
				}
			},
			"additionalProperties": true
		}
	},
	"additionalProperties": true
}

=== MSSGIT2128/MSS_UAT/NetSuiteWebhook/NetSuiteWebhook/Files/NS_FU/NetSuite/Sample Payloads/CreateCustomerMSSContactAssignmentSample.json
{
"RequestId": 654567898765434,
  "Operation": "Create",
  "Type": "MSSContactAssignment",
  "Data": {
    "CustomerAccountId": "300000003444564",
    "PartyId": "300000003444540",

      "CustomerAccountContact": {
        "CustomerAccountId": "300000003444564",
        "PrimaryFlag": false,
        "RoleType": "CONTACT",
        "CreatedByModule": "SIS",
        "RelationshipId": "300000003444691",
        "CustomerAccountContactRole": {
          "ResponsibilityType": "BILL_TO",
          "PrimaryFlag": true,
          "CreatedByModule": "SIS"
        }
      
    }
  }
}
