=== MSSGIT2128/MSS_UAT/CopyOfRolecall_To_Fusion/Files/NS_FU/Fusion/Dimensions/CustomerMapping/Response/ResponseSchmea.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"$id": "http://example.com/example.json",
	"type": "object",
	"title": "The root schema",
	"description": "The root schema comprises the entire JSON document.",
	"default": {},
	"examples": [
		{
			"ValueId": 262001,
			"IndependentValue": null,
			"IndependentValueNumber": null,
			"IndependentValueDate": null,
			"IndependentValueTimestamp": null,
			"Value": "MgTEST003|CONT003|40009|029|100|999",
			"ValueNumber": null,
			"ValueDate": null,
			"ValueTimestamp": null,
			"TranslatedValue": null,
			"Description": "TEST003_NAME|CONT003_NAME",
			"EnabledFlag": "N",
			"StartDateActive": "2018-01-01",
			"EndDateActive": null,
			"SortOrder": null,
			"SummaryFlag": "N",
			"DetailPostingAllowed": "N",
			"DetailBudgetingAllowed": "N",
			"AccountType": null,
			"ControlAccount": null,
			"ReconciliationFlag": null,
			"FinancialCategory": null,
			"ExternalDataSource": null,
			"CreationDate": "2021-02-17T14:23:32+00:00",
			"CreatedBy": "SIS_INTEGRATION",
			"LastUpdateDate": "2021-02-17T14:23:33.041+00:00",
			"LastUpdatedBy": "SIS_INTEGRATION",
			"links": [
				{
					"rel": "self",
					"href": "https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/SIS_CUSTOMER_MAPPING/child/values/262001",
					"name": "values",
					"kind": "item"
				},
				{
					"rel": "canonical",
					"href": "https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/SIS_CUSTOMER_MAPPING/child/values/262001",
					"name": "values",
					"kind": "item"
				},
				{
					"rel": "parent",
					"href": "https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/SIS_CUSTOMER_MAPPING",
					"name": "valueSets",
					"kind": "item"
				},
				{
					"rel": "child",
					"href": "https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/SIS_CUSTOMER_MAPPING/child/values/262001/child/valuesDFF",
					"name": "valuesDFF",
					"kind": "collection"
				}
			]
		}
	],
	"required": [
		"ValueId",
		"IndependentValue",
		"IndependentValueNumber",
		"IndependentValueDate",
		"IndependentValueTimestamp",
		"Value",
		"ValueNumber",
		"ValueDate",
		"ValueTimestamp",
		"TranslatedValue",
		"Description",
		"EnabledFlag",
		"StartDateActive",
		"EndDateActive",
		"SortOrder",
		"SummaryFlag",
		"DetailPostingAllowed",
		"DetailBudgetingAllowed",
		"AccountType",
		"ControlAccount",
		"ReconciliationFlag",
		"FinancialCategory",
		"ExternalDataSource",
		"CreationDate",
		"CreatedBy",
		"LastUpdateDate",
		"LastUpdatedBy",
		"links"
	],
	"properties": {
		"ValueId": {
			"$id": "#/properties/ValueId",
			"type": "integer",
			"title": "The ValueId schema",
			"description": "An explanation about the purpose of this instance.",
			"default": 0,
			"examples": [
				262001
			]
		},
		"IndependentValue": {
			"$id": "#/properties/IndependentValue",
			"type": "null",
			"title": "The IndependentValue schema",
			"description": "An explanation about the purpose of this instance.",
			"default": null,
			"examples": [
				null
			]
		},
		"IndependentValueNumber": {
			"$id": "#/properties/IndependentValueNumber",
			"type": "null",
			"title": "The IndependentValueNumber schema",
			"description": "An explanation about the purpose of this instance.",
			"default": null,
			"examples": [
				null
			]
		},
		"IndependentValueDate": {
			"$id": "#/properties/IndependentValueDate",
			"type": "null",
			"title": "The IndependentValueDate schema",
			"description": "An explanation about the purpose of this instance.",
			"default": null,
			"examples": [
				null
			]
		},
		"IndependentValueTimestamp": {
			"$id": "#/properties/IndependentValueTimestamp",
			"type": "null",
			"title": "The IndependentValueTimestamp schema",
			"description": "An explanation about the purpose of this instance.",
			"default": null,
			"examples": [
				null
			]
		},
		"Value": {
			"$id": "#/properties/Value",
			"type": "string",
			"title": "The Value schema",
			"description": "An explanation about the purpose of this instance.",
			"default": "",
			"examples": [
				"MgTEST003|CONT003|40009|029|100|999"
			]
		},
		"ValueNumber": {
			"$id": "#/properties/ValueNumber",
			"type": "null",
			"title": "The ValueNumber schema",
			"description": "An explanation about the purpose of this instance.",
			"default": null,
			"examples": [
				null
			]
		},
		"ValueDate": {
			"$id": "#/properties/ValueDate",
			"type": "null",
			"title": "The ValueDate schema",
			"description": "An explanation about the purpose of this instance.",
			"default": null,
			"examples": [
				null
			]
		},
		"ValueTimestamp": {
			"$id": "#/properties/ValueTimestamp",
			"type": "null",
			"title": "The ValueTimestamp schema",
			"description": "An explanation about the purpose of this instance.",
			"default": null,
			"examples": [
				null
			]
		},
		"TranslatedValue": {
			"$id": "#/properties/TranslatedValue",
			"type": "null",
			"title": "The TranslatedValue schema",
			"description": "An explanation about the purpose of this instance.",
			"default": null,
			"examples": [
				null
			]
		},
		"Description": {
			"$id": "#/properties/Description",
			"type": "string",
			"title": "The Description schema",
			"description": "An explanation about the purpose of this instance.",
			"default": "",
			"examples": [
				"TEST003_NAME|CONT003_NAME"
			]
		},
		"EnabledFlag": {
			"$id": "#/properties/EnabledFlag",
			"type": "string",
			"title": "The EnabledFlag schema",
			"description": "An explanation about the purpose of this instance.",
			"default": "",
			"examples": [
				"N"
			]
		},
		"StartDateActive": {
			"$id": "#/properties/StartDateActive",
			"type": "string",
			"title": "The StartDateActive schema",
			"description": "An explanation about the purpose of this instance.",
			"default": "",
			"examples": [
				"2018-01-01"
			]
		},
		"EndDateActive": {
			"$id": "#/properties/EndDateActive",
			"type": "null",
			"title": "The EndDateActive schema",
			"description": "An explanation about the purpose of this instance.",
			"default": null,
			"examples": [
				null
			]
		},
		"SortOrder": {
			"$id": "#/properties/SortOrder",
			"type": "null",
			"title": "The SortOrder schema",
			"description": "An explanation about the purpose of this instance.",
			"default": null,
			"examples": [
				null
			]
		},
		"SummaryFlag": {
			"$id": "#/properties/SummaryFlag",
			"type": "string",
			"title": "The SummaryFlag schema",
			"description": "An explanation about the purpose of this instance.",
			"default": "",
			"examples": [
				"N"
			]
		},
		"DetailPostingAllowed": {
			"$id": "#/properties/DetailPostingAllowed",
			"type": "string",
			"title": "The DetailPostingAllowed schema",
			"description": "An explanation about the purpose of this instance.",
			"default": "",
			"examples": [
				"N"
			]
		},
		"DetailBudgetingAllowed": {
			"$id": "#/properties/DetailBudgetingAllowed",
			"type": "string",
			"title": "The DetailBudgetingAllowed schema",
			"description": "An explanation about the purpose of this instance.",
			"default": "",
			"examples": [
				"N"
			]
		},
		"AccountType": {
			"$id": "#/properties/AccountType",
			"type": "null",
			"title": "The AccountType schema",
			"description": "An explanation about the purpose of this instance.",
			"default": null,
			"examples": [
				null
			]
		},
		"ControlAccount": {
			"$id": "#/properties/ControlAccount",
			"type": "null",
			"title": "The ControlAccount schema",
			"description": "An explanation about the purpose of this instance.",
			"default": null,
			"examples": [
				null
			]
		},
		"ReconciliationFlag": {
			"$id": "#/properties/ReconciliationFlag",
			"type": "null",
			"title": "The ReconciliationFlag schema",
			"description": "An explanation about the purpose of this instance.",
			"default": null,
			"examples": [
				null
			]
		},
		"FinancialCategory": {
			"$id": "#/properties/FinancialCategory",
			"type": "null",
			"title": "The FinancialCategory schema",
			"description": "An explanation about the purpose of this instance.",
			"default": null,
			"examples": [
				null
			]
		},
		"ExternalDataSource": {
			"$id": "#/properties/ExternalDataSource",
			"type": "null",
			"title": "The ExternalDataSource schema",
			"description": "An explanation about the purpose of this instance.",
			"default": null,
			"examples": [
				null
			]
		},
		"CreationDate": {
			"$id": "#/properties/CreationDate",
			"type": "string",
			"title": "The CreationDate schema",
			"description": "An explanation about the purpose of this instance.",
			"default": "",
			"examples": [
				"2021-02-17T14:23:32+00:00"
			]
		},
		"CreatedBy": {
			"$id": "#/properties/CreatedBy",
			"type": "string",
			"title": "The CreatedBy schema",
			"description": "An explanation about the purpose of this instance.",
			"default": "",
			"examples": [
				"SIS_INTEGRATION"
			]
		},
		"LastUpdateDate": {
			"$id": "#/properties/LastUpdateDate",
			"type": "string",
			"title": "The LastUpdateDate schema",
			"description": "An explanation about the purpose of this instance.",
			"default": "",
			"examples": [
				"2021-02-17T14:23:33.041+00:00"
			]
		},
		"LastUpdatedBy": {
			"$id": "#/properties/LastUpdatedBy",
			"type": "string",
			"title": "The LastUpdatedBy schema",
			"description": "An explanation about the purpose of this instance.",
			"default": "",
			"examples": [
				"SIS_INTEGRATION"
			]
		},
		"links": {
			"$id": "#/properties/links",
			"type": "array",
			"title": "The links schema",
			"description": "An explanation about the purpose of this instance.",
			"default": [],
			"examples": [
				[
					{
						"rel": "self",
						"href": "https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/SIS_CUSTOMER_MAPPING/child/values/262001",
						"name": "values",
						"kind": "item"
					},
					{
						"rel": "canonical",
						"href": "https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/SIS_CUSTOMER_MAPPING/child/values/262001",
						"name": "values",
						"kind": "item"
					}
				]
			],
			"additionalItems": true,
			"items": {
				"$id": "#/properties/links/items",
				"anyOf": [
					{
						"$id": "#/properties/links/items/anyOf/0",
						"type": "object",
						"title": "The first anyOf schema",
						"description": "An explanation about the purpose of this instance.",
						"default": {},
						"examples": [
							{
								"rel": "self",
								"href": "https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/SIS_CUSTOMER_MAPPING/child/values/262001",
								"name": "values",
								"kind": "item"
							}
						],
						"required": [
							"rel",
							"href",
							"name",
							"kind"
						],
						"properties": {
							"rel": {
								"$id": "#/properties/links/items/anyOf/0/properties/rel",
								"type": "string",
								"title": "The rel schema",
								"description": "An explanation about the purpose of this instance.",
								"default": "",
								"examples": [
									"self"
								]
							},
							"href": {
								"$id": "#/properties/links/items/anyOf/0/properties/href",
								"type": "string",
								"title": "The href schema",
								"description": "An explanation about the purpose of this instance.",
								"default": "",
								"examples": [
									"https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/SIS_CUSTOMER_MAPPING/child/values/262001"
								]
							},
							"name": {
								"$id": "#/properties/links/items/anyOf/0/properties/name",
								"type": "string",
								"title": "The name schema",
								"description": "An explanation about the purpose of this instance.",
								"default": "",
								"examples": [
									"values"
								]
							},
							"kind": {
								"$id": "#/properties/links/items/anyOf/0/properties/kind",
								"type": "string",
								"title": "The kind schema",
								"description": "An explanation about the purpose of this instance.",
								"default": "",
								"examples": [
									"item"
								]
							}
						},
						"additionalProperties": true
					}
				]
			}
		}
	},
	"additionalProperties": true
}

=== MSSGIT2128/MSS_UAT/DunningLetters/DunningLetters/Files/Fusion/CustomerCommunication/Response/SampleResponse.json
{
	"ValueId": 262001,
	"IndependentValue": null,
	"IndependentValueNumber": null,
	"IndependentValueDate": null,
	"IndependentValueTimestamp": null,
	"Value": "MgTEST003|CONT003|40009|029|100|999",
	"ValueNumber": null,
	"ValueDate": null,
	"ValueTimestamp": null,
	"TranslatedValue": null,
	"Description": "TEST003_NAME|CONT003_NAME",
	"EnabledFlag": "N",
	"StartDateActive": "2018-01-01",
	"EndDateActive": null,
	"SortOrder": null,
	"SummaryFlag": "N",
	"DetailPostingAllowed": "N",
	"DetailBudgetingAllowed": "N",
	"AccountType": null,
	"ControlAccount": null,
	"ReconciliationFlag": null,
	"FinancialCategory": null,
	"ExternalDataSource": null,
	"CreationDate": "2021-02-17T14:23:32+00:00",
	"CreatedBy": "SIS_INTEGRATION",
	"LastUpdateDate": "2021-02-17T14:23:33.041+00:00",
	"LastUpdatedBy": "SIS_INTEGRATION",
	"links": [
		{
			"rel": "self",
			"href": "https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/SIS_CUSTOMER_MAPPING/child/values/262001",
			"name": "values",
			"kind": "item"
		},
		{
			"rel": "canonical",
			"href": "https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/SIS_CUSTOMER_MAPPING/child/values/262001",
			"name": "values",
			"kind": "item"
		},
		{
			"rel": "parent",
			"href": "https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/SIS_CUSTOMER_MAPPING",
			"name": "valueSets",
			"kind": "item"
		},
		{
			"rel": "child",
			"href": "https://fa-epnz-test-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/SIS_CUSTOMER_MAPPING/child/values/262001/child/valuesDFF",
			"name": "valuesDFF",
			"kind": "collection"
		}
	]
}

=== MSSGIT2128/MSS_UAT/CopyOfRolecall_To_Fusion/Files/RoleCall_FU/Fusion/Customer/COACreateCustomerSite/Response/CreateCustomerSiteResponseSample.json
{
	"ValueId": 107001,
	"IndependentValue": null,
	"IndependentValueNumber": null,
	"IndependentValueDate": null,
	"IndependentValueTimestamp": null,
	"Value": "99910",
	"ValueNumber": null,
	"ValueDate": null,
	"ValueTimestamp": null,
	"TranslatedValue": null,
	"Description": "COGNIZANT TECHNOLOGY SOLUTIONS INDIA PVT LTD1",
	"EnabledFlag": "Y",
	"StartDateActive": "2020-01-01",
	"EndDateActive": null,
	"SortOrder": null,
	"SummaryFlag": "Y",
	"DetailPostingAllowed": "N",
	"DetailBudgetingAllowed": "N",
	"AccountType": null,
	"ControlAccount": null,
	"ReconciliationFlag": null,
	"FinancialCategory": null,
	"ExternalDataSource": null,
	"CreationDate": "2020-12-18T06:29:53+00:00",
	"CreatedBy": "SIS_INTEGRATION",
	"LastUpdateDate": "2020-12-18T06:30:03.489+00:00",
	"LastUpdatedBy": "SIS_INTEGRATION",
	"links": [
		{
			"rel": "self",
			"href": "https://fa-epnz-dev1-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/Customer%20Site%20SIS_COA/child/values/107001",
			"name": "values",
			"kind": "item"
		},
		{
			"rel": "canonical",
			"href": "https://fa-epnz-dev1-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/Customer%20Site%20SIS_COA/child/values/107001",
			"name": "values",
			"kind": "item"
		},
		{
			"rel": "parent",
			"href": "https://fa-epnz-dev1-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/Customer%20Site%20SIS_COA",
			"name": "valueSets",
			"kind": "item"
		},
		{
			"rel": "child",
			"href": "https://fa-epnz-dev1-saasfaprod1.fa.ocs.oraclecloud.com:443/fscmRestApi/resources/11.13.18.05/valueSets/Customer%20Site%20SIS_COA/child/values/107001/child/valuesDFF",
			"name": "valuesDFF",
			"kind": "collection"
		}
	]
}
